[package]
name = "baby-name-tournament"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-channel = "1"
clap = { version = "4", features = ["derive", "env"] }
dotenvy = "0.15"
csv = "1"
futures-util = { version = "0.3", default-features = false }
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.6", features = ["sqlite", "runtime-tokio-rustls", "offline"] }
tokio = { version = "1", features = ["rt", "macros"] }
url = "2"
