name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '52 21 * * 3'

env:
  SQLX_OFFLINE: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Install GTK4
        run: sudo apt-get update && sudo apt-get install -y libgtk-4-dev libadwaita-1-dev
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2.7.7
      - name: Check
        run: cargo check --workspace --tests
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install GTK4
        run: sudo apt-get update && sudo apt-get install -y libgtk-4-dev libadwaita-1-dev
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@1.83
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2.7.7
      - name: Clippy
        run: cargo clippy --workspace --tests -- -Dwarnings
  formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@1.83
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2.7.7
      - name: Check formatting
        run: cargo fmt --all -- --check
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install GTK4
        run: sudo apt-get update && sudo apt-get install -y libgtk-4-dev libadwaita-1-dev
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@1.83
      - uses: Swatinem/rust-cache@v2.7.7
      - name: Build
        run: cargo build --workspace --tests
      - name: Run tests
        run: cargo test --workspace
  dependencies:
    name: Check dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Cargo deny
        uses: EmbarkStudios/cargo-deny-action@v2.0.11
        with:
          command: check bans licenses sources advisories
